### ISSUE TITLE
 `instance_variable_set': can't modify frozen NilClass (RuntimeError)

### ISSUE THREAD

**Issue by aliceinwire** [aliceinwire/wikinote2#5]
```
/home/alicef/.gem/ruby/2.3.0/gems/haml-5.0.4/lib/haml/engine.rb:132:in `instance_variable_set': can't modify frozen NilClass (RuntimeError)
        from /home/alicef/.gem/ruby/2.3.0/gems/haml-5.0.4/lib/haml/engine.rb:132:in `ensure in render'
        from /home/alicef/.gem/ruby/2.3.0/gems/haml-5.0.4/lib/haml/engine.rb:132:in `render'
        from /home/alicef/.gem/ruby/2.3.0/gems/soywiki-0.9.8.3/lib/soywiki/html.rb:79:in `generate_page'
        from /home/alicef/.gem/ruby/2.3.0/gems/soywiki-0.9.8.3/lib/soywiki/html.rb:57:in `block in make_pages'
        from /home/alicef/.gem/ruby/2.3.0/gems/soywiki-0.9.8.3/lib/soywiki/html.rb:55:in `each'
        from /home/alicef/.gem/ruby/2.3.0/gems/soywiki-0.9.8.3/lib/soywiki/html.rb:55:in `make_pages'
        from /home/alicef/.gem/ruby/2.3.0/gems/soywiki-0.9.8.3/lib/soywiki/html.rb:27:in `block in export'
        from /home/alicef/.gem/ruby/2.3.0/gems/soywiki-0.9.8.3/lib/soywiki/html.rb:26:in `each'
        from /home/alicef/.gem/ruby/2.3.0/gems/soywiki-0.9.8.3/lib/soyw
```

**Comment by aliceinwire** [comment]
fixed in #6
